<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Mulai Beriklan</name>
   <tag></tag>
   <elementGuidId>9bbf6d48-2202-46ac-abc3-571a4f958687</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@type='button']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>805a68f8-8095-4806-ab54-25bb08f2d706</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>efb4f314-66da-4aff-bfde-a0b60ad26857</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>px-16 py-4 flex bg-[#04E3F4] rounded-full text-primary</value>
      <webElementGuid>41794323-3f24-4029-9a56-e6bf03251d15</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Mulai Beriklan</value>
      <webElementGuid>e251353f-c792-4c40-a08c-d1c104abf8b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;__className_85d873&quot;]/section[@class=&quot;mt-48 bg-primary w-full pb-20 lg:pb-0&quot;]/div[@class=&quot;flex flex-col-reverse lg:flex-row justify-between items-center lg:items-start xl:items-center max-[450px]:h-[25.25rem]&quot;]/div[@class=&quot;lg:py-32 px-5 lg:pl-44 sm:flex sm:flex-col sm:justify-center sm:items-center lg:block&quot;]/div[@class=&quot;pt-8 sm:pt-12&quot;]/button[@class=&quot;px-16 py-4 flex bg-[#04E3F4] rounded-full text-primary&quot;]</value>
      <webElementGuid>d717958e-c03f-4c2c-8c8f-98cac4c8b272</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_HIGO  WiFi Advertising Platform dengan_f9297b/iframe_Bahasa_react-iframe-container</value>
      <webElementGuid>b1dfe2d7-6578-4228-a1d6-ad970b77c31e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@type='button']</value>
      <webElementGuid>deee6faf-8474-4c86-9d2f-4e4ee9507089</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/section[4]/div/div/div/button</value>
      <webElementGuid>bb37a65b-422b-4e49-8cf8-ea028eb253c7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Jangkau target audiens dengan berbagai platform media'])[1]/following::button[1]</value>
      <webElementGuid>2eb047cf-a61a-4743-9c81-0e44b5ef7f3e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Partner Kami'])[1]/following::button[1]</value>
      <webElementGuid>acfeb939-5eae-4b5b-b6c5-f9d2aaacde59</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='About Us'])[1]/preceding::button[1]</value>
      <webElementGuid>3ebe7ca1-bea3-46cf-8b2a-3922f3a1bd3e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Career'])[1]/preceding::button[1]</value>
      <webElementGuid>e820c9db-6872-4e1e-9c29-fbd7d79de8c8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Mulai Beriklan']/parent::*</value>
      <webElementGuid>55691eed-d70a-474f-8b64-aa5a7727ee77</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button</value>
      <webElementGuid>4f1a9855-b67c-48f8-9756-e2babdfd8bce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = 'Mulai Beriklan' or . = 'Mulai Beriklan')]</value>
      <webElementGuid>30acbef6-2c3e-431c-9dfc-b097a9b7f9a4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
