<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Lihat Lokasi HIGOspot_sacled</name>
   <tag></tag>
   <elementGuidId>bb9b1afd-a0c1-4ddb-9179-b1287f37d393</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img.sacled</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='outer-container']/div/div[4]/div[3]/div/button/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>87585acb-4724-4ad2-88f6-e9ea9523a317</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/img/Group 373-min.f75943e8.png</value>
      <webElementGuid>d615af23-959c-4009-b646-f323318e0419</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>location-1</value>
      <webElementGuid>37592d69-3df2-495e-a1a6-184c9abf4b0a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sacled</value>
      <webElementGuid>d7c231e6-7dbc-473d-8496-e7eacc614479</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;outer-container&quot;)/div[@class=&quot;home-container&quot;]/div[@class=&quot;location-container&quot;]/div[@class=&quot;content-location&quot;]/div[@class=&quot;card&quot;]/button[@class=&quot;img-wrapper&quot;]/img[@class=&quot;sacled&quot;]</value>
      <webElementGuid>b2c72b99-ba90-4e54-bafa-d2aabbba5a76</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='outer-container']/div/div[4]/div[3]/div/button/img</value>
      <webElementGuid>a2ce903f-a337-43b4-9afa-a0544172e1a1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='location-1']</value>
      <webElementGuid>d23b79d6-3838-4fa8-b5b7-12f618bd4414</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button/img</value>
      <webElementGuid>54bb8595-7c4b-45fa-9fb9-854c1a187eaa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '/img/Group 373-min.f75943e8.png' and @alt = 'location-1']</value>
      <webElementGuid>63bb54ab-c439-4585-8366-89d852475a78</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
