<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_Lifestyle</name>
   <tag></tag>
   <elementGuidId>f95cbd6c-123c-4479-bba5-e919e4b2e416</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//div[@id='cat-tgl']/p)[5]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>85c5f0de-be5d-45b4-826b-e58d16dae221</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text-white text-sm mr-5</value>
      <webElementGuid>d9ec727a-5fd7-4a81-95d9-2a6ac372eca6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Lifestyle</value>
      <webElementGuid>752e6c7c-62e8-4371-b917-6ddc11c33390</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;carousel-container&quot;)/div[@class=&quot;react-multi-carousel-list  w-full h-full rounded&quot;]/ul[@class=&quot;react-multi-carousel-track&quot;]/li[@class=&quot;react-multi-carousel-item react-multi-carousel-item--active&quot;]/div[@class=&quot;w-full sm:w-11/12 md:w-full sm:mx-auto h-80 lg:h-lg xl:h-xl 2xl:h-2xl white pb-10&quot;]/div[@class=&quot;w-full h-full bg-gray-300&quot;]/div[@class=&quot;w-full h-full&quot;]/a[@class=&quot;cursor-pointer&quot;]/div[@class=&quot;md:px-5 relative w-full h-full&quot;]/div[@id=&quot;card-info&quot;]/div[@class=&quot;absolute bottom-2 md:bottom-4 w-auto h-auto&quot;]/div[@id=&quot;cat-tgl&quot;]/p[@class=&quot;text-white text-sm mr-5&quot;]</value>
      <webElementGuid>de1afaaa-d72b-4ad9-836a-002360b86829</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>(//div[@id='cat-tgl']/p)[5]</value>
      <webElementGuid>532c0309-6136-40b4-8ad3-d17e667fd6ce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mengulik Alasan Pizza Hut Ganti Nama Jadi Ristorante'])[1]/following::p[2]</value>
      <webElementGuid>ca576520-1fd9-4fcb-ad95-791a434ea50d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Rekomendasi NGO Pecinta Lingkungan di Indonesia'])[1]/following::p[5]</value>
      <webElementGuid>2ed3c9e8-c7ce-4645-b8bf-5f36d14b2b90</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Rekomendasi Netflix Untuk Temani Awal Tahun 2024'])[1]/preceding::p[2]</value>
      <webElementGuid>d38c0f75-d40b-419b-8ff1-0809e8c35623</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Rekomendasi NGO Pecinta Lingkungan di Indonesia'])[2]/preceding::p[5]</value>
      <webElementGuid>be2be5f7-9adc-49f8-abb3-eb188116ee90</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[3]/div/div/div/a/div/div/div/div/p</value>
      <webElementGuid>f5396a3e-2b16-4809-977f-f4face201dfb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[(text() = 'Lifestyle' or . = 'Lifestyle')]</value>
      <webElementGuid>fff72033-63c5-46b8-8099-38e7dc4472b4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
