<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Blog</name>
   <tag></tag>
   <elementGuidId>44757b50-5432-46b2-9a1d-9e6ee93248f5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='blog']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#blog</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>51e31d3e-9cd0-443e-b407-6609b178fd76</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>blog</value>
      <webElementGuid>61fb3c4f-7821-43c3-a67f-249a454bba0c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
        Blog
      </value>
      <webElementGuid>e5e1159e-fe54-463a-a6dc-9b8ff5fc3073</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;blog&quot;)</value>
      <webElementGuid>23654618-8e2c-46b5-860d-2d4cf5181bb6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='blog']</value>
      <webElementGuid>5f160b1e-a3dd-4f07-83d7-2a1ef6eb2223</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='outer-container']/div[2]/div[3]/header/div[2]/div[5]/div</value>
      <webElementGuid>979cbeb2-56cc-4f28-8e7f-8d34d25422ca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Studi Kasus'])[1]/following::div[2]</value>
      <webElementGuid>1c991123-365b-4018-8ed5-c4a15ee05beb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Integrated Digital Agency'])[1]/following::div[3]</value>
      <webElementGuid>b60c8c8b-c467-4618-99ec-7100d420f7fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Hubungi Kami'])[1]/preceding::div[1]</value>
      <webElementGuid>f0d23d92-274e-4145-9af8-19673d8bb034</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Bahasa'])[1]/preceding::div[3]</value>
      <webElementGuid>f70912af-5c71-4859-89a0-abc709f612b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Blog']/parent::*</value>
      <webElementGuid>522c326c-46ff-4e46-9412-5a88680cdaa2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//header/div[2]/div[5]/div</value>
      <webElementGuid>c22f6aad-ecb4-4f8b-820b-e616f5006468</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'blog' and (text() = '
        Blog
      ' or . = '
        Blog
      ')]</value>
      <webElementGuid>b28df978-fd89-4527-ac55-a2ec92437497</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
