<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_Bahasa_react-iframe-container (10)</name>
   <tag></tag>
   <elementGuidId>0c1996b5-b6b5-4873-8b8b-26f1770d50cc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='app']/div/iframe</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>iframe.react-iframe-container</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>b19ba7ad-65b9-4aad-9b50-7222cf1dad76</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://new.higo.id/wifi-advertising</value>
      <webElementGuid>ea4e1d2f-72f2-44d7-bfec-d056523db9b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>78b7d833-8125-4ec2-9214-b16dc29edabd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>react-iframe-container</value>
      <webElementGuid>360d7833-1f5a-4aca-ac27-73da0bf478a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/div[1]/iframe[@class=&quot;react-iframe-container&quot;]</value>
      <webElementGuid>d8dfbb5c-de13-44f8-abf8-7f6fa5b26df2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/iframe</value>
      <webElementGuid>6f01147a-49c3-49db-b194-62cadf25bb9b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>aa4c5316-a759-42f8-aba3-25576295c27a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@src = 'https://new.higo.id/wifi-advertising']</value>
      <webElementGuid>02b4d6e6-4462-4956-839e-afdb699cbc53</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
