<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_Bahasa_react-iframe-container (26)</name>
   <tag></tag>
   <elementGuidId>d99445d9-8ebb-4fd3-85d9-cc568c640ef4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='app']/div/iframe</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>iframe.react-iframe-container</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>6cd84370-a138-4f95-9d6c-c90844f8e74e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://new.higo.id/wifi-advertising</value>
      <webElementGuid>9928b75a-18d5-4880-8a04-41675e156fba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>1ce5ae71-bbb4-4be1-985f-55cdf2354ac7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>react-iframe-container</value>
      <webElementGuid>13c9c154-55e9-4147-b9c0-bf3bdbe580bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/div[1]/iframe[@class=&quot;react-iframe-container&quot;]</value>
      <webElementGuid>16f26a8a-baa1-4b3b-90fa-0d756b2680ee</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/iframe</value>
      <webElementGuid>6fe847f8-6556-4cc7-956a-0b365b28811a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>cbc3c999-0a92-4afb-a708-66c048b445bf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@src = 'https://new.higo.id/wifi-advertising']</value>
      <webElementGuid>a313c45a-6cd4-4791-884f-13e1e2af256e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
