<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_Bahasa_react-iframe-container (18)</name>
   <tag></tag>
   <elementGuidId>a8a6f73f-9868-4c50-8802-c106aa2874bb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='app']/div/iframe</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>iframe.react-iframe-container</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>bcca1e0f-4b8d-4fc0-8a2f-75a350c20e05</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://new.higo.id/wifi-advertising</value>
      <webElementGuid>a9be32f0-afe1-482a-bb69-7927c22dac92</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>812050f2-906e-48a0-ac03-8e7c480502a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>react-iframe-container</value>
      <webElementGuid>f2c029ed-1fd1-4dca-8d68-103d28a55b2a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/div[1]/iframe[@class=&quot;react-iframe-container&quot;]</value>
      <webElementGuid>2af4ef5b-0be0-4010-88c9-37f14f09173f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/iframe</value>
      <webElementGuid>74fa227a-dea1-464b-bb82-b4f80684640c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>01dc81bd-3dc5-4bac-97e1-c94ad9a8eab0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@src = 'https://new.higo.id/wifi-advertising']</value>
      <webElementGuid>03c31b72-697d-41a9-a73b-66127c96573d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
