<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_Bahasa_react-iframe-container (8)</name>
   <tag></tag>
   <elementGuidId>fb9f38ef-2631-46c7-a920-b0d8ef3512ec</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='app']/div/iframe</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>iframe.react-iframe-container</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>037f02e1-1d95-4e9a-b906-6723bb16d468</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://new.higo.id/wifi-advertising</value>
      <webElementGuid>3933ad87-e5a7-458a-90db-7cb02badc75c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>9b07afbe-fe17-4dc9-9306-5d4d27b84142</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>react-iframe-container</value>
      <webElementGuid>d16a89c4-52fd-47de-85d2-b6ab82d62290</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/div[1]/iframe[@class=&quot;react-iframe-container&quot;]</value>
      <webElementGuid>89e54bb3-fd2c-4f41-a31c-9d21c27a1c24</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/iframe</value>
      <webElementGuid>afd709b6-4bdb-4bf3-b39a-58af5c9129fc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>2ab05554-6a04-43c7-a0c4-c483e19694f6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@src = 'https://new.higo.id/wifi-advertising']</value>
      <webElementGuid>5a7a17ca-314c-423e-8a43-b3495faf0949</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
