<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_Bahasa_react-iframe-container</name>
   <tag></tag>
   <elementGuidId>c4f77954-67ab-46e6-a7d3-72aecd002420</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='app']/div/iframe</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>iframe.react-iframe-container</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>a565f4dd-f12b-4634-855b-088f86f2ccd4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://new.higo.id/wifi-advertising</value>
      <webElementGuid>f5ed44ec-e5db-445a-a377-857c0d4f010e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>53b59967-63cc-48ae-9b0a-45fcd2cbdb7a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>react-iframe-container</value>
      <webElementGuid>559ed77a-bbfd-4ee7-a230-219a5bb4a711</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/div[1]/iframe[@class=&quot;react-iframe-container&quot;]</value>
      <webElementGuid>d3461fc9-916f-45ad-a6ff-72900c8d16f0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/iframe</value>
      <webElementGuid>c96b0bdf-d312-449b-a98a-79b9876e64a6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>deb08e28-900b-4a52-82fa-cc8145fb0029</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@src = 'https://new.higo.id/wifi-advertising']</value>
      <webElementGuid>4179f879-f0f4-4884-85b6-3a30a63deb3e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
