<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Hubungi Kami_fixed z-50 bg-black bg-_927cd4</name>
   <tag></tag>
   <elementGuidId>3f280e75-be5b-46b0-bee6-8a81bc6884de</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/div/nav[2]/button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>3b29487c-e536-4f4f-b3a7-9b94f3c536ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fixed z-50 bg-black bg-opacity-70 bottom-32 right-0 md:right-28  lg:rounded-lg rounded-l-lg md:w-14 md:h-14 w-12 h-12 border-2 shadow-2xl</value>
      <webElementGuid>c4992722-d76d-422d-9cf4-8cdfe8aa2140</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;w-full&quot;]/nav[@class=&quot;navbar scrolled w-full px5 shadow-md h-14&quot;]/button[@class=&quot;fixed z-50 bg-black bg-opacity-70 bottom-32 right-0 md:right-28  lg:rounded-lg rounded-l-lg md:w-14 md:h-14 w-12 h-12 border-2 shadow-2xl&quot;]</value>
      <webElementGuid>25b41d4d-e138-4889-8069-6f71949d0fb0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/nav[2]/button</value>
      <webElementGuid>7d9c8998-fb3c-4e6d-9a00-c00043a92624</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Hubungi Kami'])[1]/following::button[2]</value>
      <webElementGuid>fee715b8-7284-4b11-94c1-dfafeb0c4804</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Blog'])[1]/following::button[2]</value>
      <webElementGuid>51ca7d69-2081-4d30-ba79-f8c6bfcaac5c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='All'])[1]/preceding::button[1]</value>
      <webElementGuid>2d1a3b12-8a8d-4f0a-b3ac-e9c941c45fb2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='HIGOes Update'])[1]/preceding::button[1]</value>
      <webElementGuid>bbf8fcd3-9dbc-44ba-9da8-13179101f11e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//nav[2]/button</value>
      <webElementGuid>e5c67f4d-083c-44ac-bf46-c34bc7511855</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
