<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Tech  Social Media05 01 2024Cara Buat K_56ecbf</name>
   <tag></tag>
   <elementGuidId>f942b658-7990-4faf-9d8e-4f6ef61779ec</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#item-info</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='item-info']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>5b15e260-9e48-42d6-82cf-5ae7476e45bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>h-full w-7/12 md:w-7/12 pl-2 md:pl-4 flex flex-col justify-between</value>
      <webElementGuid>555c9296-c6d7-4efc-859b-f55fe257d4fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>item-info</value>
      <webElementGuid>38fdf9ed-47e4-4287-b92c-8fb0ff2e1c6c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Tech &amp; Social Media05 01 2024Cara Buat Konten Instagram Dalam 5 MenitDi era serba digital seperti sekarang ini, media sosial memiliki peran yang penting untuk promosi dan membangun citra se...72 Views</value>
      <webElementGuid>65d27e67-d141-4ba8-8980-8b4756b6a36d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;recent-articles-list&quot;)/div[@class=&quot;mb-4 pb-4 w-full flex h-40 xl:h-48 lg:h-44 2xl:h-56 border-b-2 border-blue-200 lg:border-b-0&quot;]/div[@id=&quot;item-info&quot;]</value>
      <webElementGuid>6e5b24ef-35c2-43d3-861f-d0030dd14184</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='item-info']</value>
      <webElementGuid>56eb550d-9e84-48eb-aeeb-ae7fd2d24252</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='recent-articles-list']/div/div[2]</value>
      <webElementGuid>494617da-894d-4f28-9918-d637e24a602e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Artikel Terkini'])[1]/following::div[6]</value>
      <webElementGuid>47051d83-e8f9-409a-90f1-8331cc63b7f9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Rekomendasi Netflix Untuk Temani Awal Tahun 2024'])[3]/following::div[7]</value>
      <webElementGuid>1c777d56-02e1-42f6-bbdd-d71ecfe76fdb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mengulik Alasan Pizza Hut Ganti Nama Jadi Ristorante'])[1]/preceding::div[8]</value>
      <webElementGuid>b285d8ee-00f1-47dc-9cf9-7d607094564f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/div[2]</value>
      <webElementGuid>9a2cb795-9567-497a-b4b8-570cb04fb785</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'item-info' and (text() = 'Tech &amp; Social Media05 01 2024Cara Buat Konten Instagram Dalam 5 MenitDi era serba digital seperti sekarang ini, media sosial memiliki peran yang penting untuk promosi dan membangun citra se...72 Views' or . = 'Tech &amp; Social Media05 01 2024Cara Buat Konten Instagram Dalam 5 MenitDi era serba digital seperti sekarang ini, media sosial memiliki peran yang penting untuk promosi dan membangun citra se...72 Views')]</value>
      <webElementGuid>9e578e6d-114a-445f-9051-461a0d73d98f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
