<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_LifestyleMengulik Alasan Pizza Hut Gant_59876e</name>
   <tag></tag>
   <elementGuidId>a31fa626-5eb1-4f08-8f0d-29663fe9e26f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//div[@id='item-info'])[7]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>a293ec22-b2e0-4e00-ba88-5d01be1892dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>h-full w-7/12 lg:w-8/12 pl-2 md:pl-4</value>
      <webElementGuid>a094eebb-43cf-442b-a220-7eb9b79d1476</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>item-info</value>
      <webElementGuid>7dee1f54-2b61-4e01-920f-f4b9a5599623</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>LifestyleMengulik Alasan Pizza Hut Ganti Nama Jadi Ristorante2.966 Views</value>
      <webElementGuid>ae89dabf-9f6c-4281-86ef-1f6f9c88e316</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;popular-items&quot;)/div[@class=&quot;mb-3 w-11/12 mx-auto md:mx-0  md:w-full flex h-40 lg:h-32 xl:h-36 2xl:h-36 pb-3 border-b-2 border-blue-200 lg:border-b-0&quot;]/div[@id=&quot;item-info&quot;]</value>
      <webElementGuid>a1632ce1-1200-465b-9d6b-c4838edab61b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//div[@id='item-info'])[7]</value>
      <webElementGuid>fa76fa0f-2a9f-481f-b725-5d4d1a0515a6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='popular-items']/div/div[2]</value>
      <webElementGuid>71628b12-26cd-47f3-aa74-d949671e196b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Artikel Populer'])[1]/following::div[5]</value>
      <webElementGuid>794f2464-673a-4d85-9fa4-13c91c159610</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Manfaat Meditasi Mindfulness Bagi Kesehetan Mental'])[1]/following::div[24]</value>
      <webElementGuid>1cf93d3f-eea7-4157-af77-4263928dff1a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mengenal CPM dan RPM: Penghasilan Para Content Creator dan Influencer'])[1]/preceding::div[11]</value>
      <webElementGuid>69898b86-7ff3-475c-b4e6-9fcc46ec965f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section/div/div/div/div[2]</value>
      <webElementGuid>4b7d9cc8-2d7d-488d-9b8d-0ee4fba7d4cd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'item-info' and (text() = 'LifestyleMengulik Alasan Pizza Hut Ganti Nama Jadi Ristorante2.966 Views' or . = 'LifestyleMengulik Alasan Pizza Hut Ganti Nama Jadi Ristorante2.966 Views')]</value>
      <webElementGuid>75a3d47b-a516-49a1-a807-0ed61bb75f7c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
