<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Artikel Populer_rounded-lg cursor-pointer</name>
   <tag></tag>
   <elementGuidId>6cffae75-990f-4f0b-b7fe-8d74241de543</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img.rounded-lg.cursor-pointer</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//div[@id='img-cont']/div/img)[7]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>2a666480-0c88-4f22-87f1-048694e41a24</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Mengulik Alasan Pizza Hut Ganti Nama Jadi Ristorante</value>
      <webElementGuid>3b5ab550-a887-40d1-9b24-88437152ab52</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>sizes</name>
      <type>Main</type>
      <value>100vw</value>
      <webElementGuid>122626f3-f84c-480b-b0fc-b28fdbf583bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>srcset</name>
      <type>Main</type>
      <value>https://imgblog.higo.id/1703043568-m.webp?w=640&amp;q=60 640w, https://imgblog.higo.id/1703043568-m.webp?w=750&amp;q=60 750w, https://imgblog.higo.id/1703043568-m.webp?w=828&amp;q=60 828w, https://imgblog.higo.id/1703043568-m.webp?w=1080&amp;q=60 1080w, https://imgblog.higo.id/1703043568-m.webp?w=1200&amp;q=60 1200w, https://imgblog.higo.id/1703043568-m.webp?w=1920&amp;q=60 1920w, https://imgblog.higo.id/1703043568-m.webp?w=2048&amp;q=60 2048w, https://imgblog.higo.id/1703043568-m.webp?w=3840&amp;q=60 3840w</value>
      <webElementGuid>a9ca2a3d-85b6-453e-9ed6-aef4f66c8501</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://imgblog.higo.id/1703043568-m.webp?w=3840&amp;q=60</value>
      <webElementGuid>7e699186-03ff-4642-9104-223ff4fb7ca6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>decoding</name>
      <type>Main</type>
      <value>async</value>
      <webElementGuid>3f76712d-dadd-4370-b4d2-792e0bf7b853</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-nimg</name>
      <type>Main</type>
      <value>fill</value>
      <webElementGuid>5432ba3d-e7ce-4bdf-9382-114c025a6ba3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>rounded-lg cursor-pointer</value>
      <webElementGuid>84c08a9b-005e-47f7-bbd4-360fd53cf04c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;popular-items&quot;)/div[@class=&quot;mb-3 w-11/12 mx-auto md:mx-0  md:w-full flex h-40 lg:h-32 xl:h-36 2xl:h-36 pb-3 border-b-2 border-blue-200 lg:border-b-0&quot;]/div[@id=&quot;img-cont&quot;]/div[1]/img[@class=&quot;rounded-lg cursor-pointer&quot;]</value>
      <webElementGuid>4146c66e-b5ec-4719-aae2-9e3910cc7090</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>(//div[@id='img-cont']/div/img)[7]</value>
      <webElementGuid>07925b90-3e72-4a6a-a6d4-7b420f2377c4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>(//img[@alt='Mengulik Alasan Pizza Hut Ganti Nama Jadi Ristorante'])[2]</value>
      <webElementGuid>5b02bcca-7ac4-48a8-8095-fdfd4cca2e8e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section/div/div/div/div/div/img</value>
      <webElementGuid>801a7b7c-7b81-4305-b0bb-3890bf3f15a8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@alt = 'Mengulik Alasan Pizza Hut Ganti Nama Jadi Ristorante' and @src = 'https://imgblog.higo.id/1703043568-m.webp?w=3840&amp;q=60']</value>
      <webElementGuid>26348464-c927-45a6-bbee-86360a571c38</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
