<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Artikel Terkini_rounded cursor-pointer</name>
   <tag></tag>
   <elementGuidId>85e2732a-84b6-47d5-ae3d-ec658fecfa93</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img.rounded.cursor-pointer</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='img-cont']/div/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>697f0c2a-8b07-40ec-8b77-03424b179aab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Cara Buat Konten Instagram Dalam 5 Menit</value>
      <webElementGuid>70f8766e-5d25-446b-9e1e-0e7e0b56a00c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://imgblog.higo.id/1704365813-m.webp?w=3840&amp;q=75</value>
      <webElementGuid>eb691342-91e3-45a5-a811-c68146980c79</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>decoding</name>
      <type>Main</type>
      <value>async</value>
      <webElementGuid>4298f633-4d7f-49bf-8d00-bc0c504ef095</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-nimg</name>
      <type>Main</type>
      <value>fill</value>
      <webElementGuid>3ba2c337-8f0f-486e-b9c8-6d43e15a477b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>rounded cursor-pointer</value>
      <webElementGuid>05722f38-012c-4268-aad0-d6f015381376</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>sizes</name>
      <type>Main</type>
      <value>100vw</value>
      <webElementGuid>185ed921-eec5-40bc-a0d4-ca4d8a45f5cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>srcset</name>
      <type>Main</type>
      <value>https://imgblog.higo.id/1704365813-m.webp?w=640&amp;q=75 640w, https://imgblog.higo.id/1704365813-m.webp?w=750&amp;q=75 750w, https://imgblog.higo.id/1704365813-m.webp?w=828&amp;q=75 828w, https://imgblog.higo.id/1704365813-m.webp?w=1080&amp;q=75 1080w, https://imgblog.higo.id/1704365813-m.webp?w=1200&amp;q=75 1200w, https://imgblog.higo.id/1704365813-m.webp?w=1920&amp;q=75 1920w, https://imgblog.higo.id/1704365813-m.webp?w=2048&amp;q=75 2048w, https://imgblog.higo.id/1704365813-m.webp?w=3840&amp;q=75 3840w</value>
      <webElementGuid>ea33a1d9-98de-415f-984c-92d5f9e110f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;recent-articles-list&quot;)/div[@class=&quot;mb-4 pb-4 w-full flex h-40 xl:h-48 lg:h-44 2xl:h-56 border-b-2 border-blue-200 lg:border-b-0&quot;]/div[@id=&quot;img-cont&quot;]/div[1]/img[@class=&quot;rounded cursor-pointer&quot;]</value>
      <webElementGuid>5671a6c2-88df-4549-8974-b77a61b6f594</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='img-cont']/div/img</value>
      <webElementGuid>c20fead5-6e8f-4d69-a2b4-63b1daa311b7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Cara Buat Konten Instagram Dalam 5 Menit']</value>
      <webElementGuid>8972d9ac-9397-4638-8625-c11db8c9dc74</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/img</value>
      <webElementGuid>168501e9-1fcb-4132-aaa1-8817a29b13b5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@alt = 'Cara Buat Konten Instagram Dalam 5 Menit' and @src = 'https://imgblog.higo.id/1704365813-m.webp?w=3840&amp;q=75']</value>
      <webElementGuid>ef93b9e1-e149-4237-8a6a-af2138eadb22</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
