<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_Hangout</name>
   <tag></tag>
   <elementGuidId>7c97f285-39e9-422c-a1f1-dc184d6e13db</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//div[@id='cat-tgl']/p)[5]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>0536e6db-ded9-477e-800d-26a08d44763d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text-white text-sm mr-5</value>
      <webElementGuid>94badc98-f71a-4bfd-bfb7-17e35b41dd33</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Hangout</value>
      <webElementGuid>64c3b67b-205d-4165-a4c5-001ea7e5f0f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;carousel-container&quot;)/div[@class=&quot;react-multi-carousel-list  w-full h-full rounded&quot;]/ul[@class=&quot;react-multi-carousel-track&quot;]/li[@class=&quot;react-multi-carousel-item react-multi-carousel-item--active&quot;]/div[@class=&quot;w-full sm:w-11/12 md:w-full sm:mx-auto h-80 lg:h-lg xl:h-xl 2xl:h-2xl white pb-10&quot;]/div[@class=&quot;w-full h-full bg-gray-300&quot;]/div[@class=&quot;w-full h-full&quot;]/a[@class=&quot;cursor-pointer&quot;]/div[@class=&quot;md:px-5 relative w-full h-full&quot;]/div[@id=&quot;card-info&quot;]/div[@class=&quot;absolute bottom-2 md:bottom-4 w-auto h-auto&quot;]/div[@id=&quot;cat-tgl&quot;]/p[@class=&quot;text-white text-sm mr-5&quot;]</value>
      <webElementGuid>3bb12799-12ea-44d6-9ea7-1eb6eebd3e4b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>(//div[@id='cat-tgl']/p)[5]</value>
      <webElementGuid>4d2047b4-54b9-429a-90ca-5891946c8120</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Seven Days Kitchen &amp; Bar, Tempat Seru Buat Hangout di Jakarta'])[1]/following::p[2]</value>
      <webElementGuid>ee44312f-65af-462c-9715-9c38dc44da6d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Rekomendasi Cafe Untuk Nongkrong di Daerah Jabodetabek'])[1]/following::p[5]</value>
      <webElementGuid>3830700d-db6d-4fc5-b30c-ead5e9ab2430</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Rekomendasi Cafe dan Coffee Shop Untuk WFC bersama Tim'])[1]/preceding::p[2]</value>
      <webElementGuid>73e73041-6499-4ebc-a251-e53f10185d2c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Rekomendasi Cafe Untuk Nongkrong di Daerah Jabodetabek'])[2]/preceding::p[5]</value>
      <webElementGuid>29d99fac-6ea6-4fc6-a507-c9c44d241118</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[3]/div/div/div/a/div/div/div/div/p</value>
      <webElementGuid>f4fbe096-ebf2-41e0-958e-e8a57fbc18c5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[(text() = 'Hangout' or . = 'Hangout')]</value>
      <webElementGuid>6540c86b-fea1-4469-9a84-bb33d291fc98</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
